const municipios_by_id: any = {
  '410': { municipio: 'JUQUITIBA', setor: 'RRDO2', divisao: 'RRDO' },
  '574': { municipio: 'REGISTRO', setor: 'RRDO2', divisao: 'RRDO' },
  '665': { municipio: 'SETE BARRAS', setor: 'RRDO2', divisao: 'RRDO' },
  '576': { municipio: 'RIBEIRA', setor: 'RRDO6', divisao: 'RRDO' },
  '203': { municipio: 'BARRA DO TURVO', setor: 'RRDO3', divisao: 'RRDO' },
  '726': { municipio: 'CAJATI', setor: 'RRDO3', divisao: 'RRDO' },
  '296': { municipio: 'ELDORADO', setor: 'RRDO3', divisao: 'RRDO' },
  '360': { municipio: 'IPORANGA', setor: 'RRDO3', divisao: 'RRDO' },
  '394': { municipio: 'JACUPIRANGA', setor: 'RRDO3', divisao: 'RRDO' },
  '351': { municipio: 'IGUAPE', setor: 'RRDO4', divisao: 'RRDO' },
  '728': { municipio: 'ILHA COMPRIDA', setor: 'RRDO4', divisao: 'RRDO' },
  '381': { municipio: 'ITARIRI', setor: 'RRDO5', divisao: 'RRDO' },
  '448': { municipio: 'MIRACATU', setor: 'RRDO5', divisao: 'RRDO' },
  '520': { municipio: 'PEDRO DE TOLEDO', setor: 'RRDO5', divisao: 'RRDO' },
  '772': { municipio: 'SAO LOURENCO DA SERRA', setor: 'RRDO2', divisao: 'RRDO' },
  '248': { municipio: 'CANANEIA', setor: 'RRDO4', divisao: 'RRDO' },
  '409': { municipio: 'JUQUIA', setor: 'RRDO5', divisao: 'RRDO' },
  '682': { municipio: 'TAPIRAI', setor: 'RRDO5', divisao: 'RRDO' },
  '176': { municipio: 'APIAI', setor: 'RRDO6', divisao: 'RRDO' },
  '750': { municipio: 'BARRA DO CHAPEU', setor: 'RRDO6', divisao: 'RRDO' },
  '753': { municipio: 'ITAOCA', setor: 'RRDO6', divisao: 'RRDO' },
  '751': { municipio: 'ITAPIRAPUA PAULISTA', setor: 'RRDO6', divisao: 'RRDO' },
  '510': { municipio: 'PARIQUERA-ACU', setor: 'RRDO4', divisao: 'RRDO' },

  '180': { municipio: 'ARANDU', setor: 'RADA1', divisao: 'RADA' },
  '194': { municipio: 'AVARE', setor: 'RADA1', divisao: 'RADA' },
  '607': { municipio: 'AGUAS DE STA BARBARA', setor: 'RADA3', divisao: 'RADA' },
  '212': { municipio: 'BERNARDINO DE CAMPOS', setor: 'RADA3', divisao: 'RADA' },
  '302': { municipio: 'FARTURA', setor: 'RADA3', divisao: 'RADA' },
  '742': { municipio: 'IARAS', setor: 'RADA3', divisao: 'RADA' },
  '486': { municipio: 'OLEO', setor: 'RADA3', divisao: 'RADA' },
  '659': { municipio: 'SARUTAIA', setor: 'RADA3', divisao: 'RADA' },
  '689': { municipio: 'TEJUPA', setor: 'RADA3', divisao: 'RADA' },
  '693': { municipio: 'TIMBURI', setor: 'RADA3', divisao: 'RADA' },
  '537': { municipio: 'PIRAJU', setor: 'RADA3', divisao: 'RADA' },
  '724': { municipio: 'ESPIRITO STO TURVO', setor: 'RADA4', divisao: 'RADA' },
  '164': { municipio: 'ALVINLANDIA', setor: 'RADA4', divisao: 'RADA' },
  '781': { municipio: 'DUARTINA', setor: 'RADA4', divisao: 'RADA' },
  '765': { municipio: 'FERNAO', setor: 'RADA4', divisao: 'RADA' },
  '314': { municipio: 'GALIA', setor: 'RADA4', divisao: 'RADA' },
  '423': { municipio: 'LUCIANOPOLIS', setor: 'RADA4', divisao: 'RADA' },
  '426': { municipio: 'LUPERCIO', setor: 'RADA4', divisao: 'RADA' },
  '768': { municipio: 'PAULISTANIA', setor: 'RADA4', divisao: 'RADA' },
  '580': { municipio: 'RIBEIRAO DO SUL', setor: 'RADA4', divisao: 'RADA' },
  '702': { municipio: 'UBIRAJARA', setor: 'RADA4', divisao: 'RADA' },
  '612': { municipio: 'STA.CRUZ DO R.PARDO', setor: 'RADA4', divisao: 'RADA' },
  '229': { municipio: 'BURI', setor: 'RADI1', divisao: 'RADI' },
  '324': { municipio: 'GUAPIARA', setor: 'RADI1', divisao: 'RADI' },
  '372': { municipio: 'ITAPEVA', setor: 'RADI1', divisao: 'RADI' },
  '754': { municipio: 'NOVA CAMPINA', setor: 'RADI1', divisao: 'RADI' },
  '756': { municipio: 'TAQUARIVAI', setor: 'RADI1', divisao: 'RADI' },
  '578': { municipio: 'RIBEIRAO BRANCO', setor: 'RADI1', divisao: 'RADI' },
  '767': { municipio: 'BOM SUCESSO ITARARE', setor: 'RADI5', divisao: 'RADI' },
  '199': { municipio: 'BARAO DE ANTONINA', setor: 'RADI5', divisao: 'RADI' },
  '376': { municipio: 'ITAPORANGA', setor: 'RADI5', divisao: 'RADI' },
  '583': { municipio: 'RIVERSUL', setor: 'RADI5', divisao: 'RADI' },
  '783': { municipio: 'ITARARE', setor: 'RADI5', divisao: 'RADI' },
  '274': { municipio: 'CORONEL MACEDO', setor: 'RADI6', divisao: 'RADI' },
  '365': { municipio: 'ITABERA', setor: 'RADI6', divisao: 'RADI' },
  '366': { municipio: 'ITAI', setor: 'RADI6', divisao: 'RADI' },
  '677': { municipio: 'TAGUAI', setor: 'RADI6', divisao: 'RADI' },
  '685': { municipio: 'TAQUARITUBA', setor: 'RADI6', divisao: 'RADI' },
  '749': { municipio: 'ALAMBARI', setor: 'RADT1', divisao: 'RADT' },
  '727': { municipio: 'CAMPINA DO MONTE ALEGRE', setor: 'RADT1', divisao: 'RADT' },
  '333': { municipio: 'GUAREI', setor: 'RADT1', divisao: 'RADT' },
  '371': { municipio: 'ITAPETININGA', setor: 'RADT1', divisao: 'RADT' },
  '506': { municipio: 'PARANAPANEMA', setor: 'RADT1', divisao: 'RADT' },
  '658': { municipio: 'SARAPUI', setor: 'RADT1', divisao: 'RADT' },
  '171': { municipio: 'ANGATUBA', setor: 'RADT1', divisao: 'RADT' },
  '527': { municipio: 'PILAR DO SUL', setor: 'RADT3', divisao: 'RADT' },
  '755': { municipio: 'RIBEIRAO GRANDE', setor: 'RADT3', divisao: 'RADT' },
  '650': { municipio: 'SAO MIGUEL ARCANJO', setor: 'RADT3', divisao: 'RADT' },
  '251': { municipio: 'CAPAO BONITO', setor: 'RADT3', divisao: 'RADT' },
};

export const getMunicipioById = (id: string) => {
  if (!municipios_by_id[id]) {
    return 'nao_cadastrato';
  }

  return municipios_by_id[id];
};
