export const permissoes: Map<string, string[]> = new Map([
  [
    "Operacional",
    [
      "São Lourenço",
      "Juquitiba",
      "Registro / Sete Barras",
      "Registro",
      "Sete Barras",
      "Barra do Turvo",
      "Cajati",
      "Cajati / Jacupiranga",
      "Eldorado",
      "Iporanga",
      "Jacupiranga",
      "Cananéia",
      "Iguape",
      "Iguape / Ilha Comprida",
      "Ilha Comprida",
      "Ilha Comprida / Pedrinhas",
      "Pariquera-Açu",
      "Itariri",
      "Juquiá",
      "Miracatu",
      "Pedro de Toledo",
      "Tapiraí",
      "Apiaí",
      "Barra do Chapéu",
      "Itaoca",
      "Itapirapuã Paulista",
      "Ribeira",
      "Ribeira / Itapirapuã Paulista",
    ],
  ],
  [
    "ETA",
    [
      "São Lourenço",
      "Juquitiba",
      "Registro",
      "Sete Barras",
      "Registro / Sete Barras",
      "Barra do Turvo",
      "Cajati",
      "Cajati / Jacupiranga",
      "Eldorado",
      "Iporanga",
      "Jacupiranga",
      "Cananéia",
      "Iguape",
      "Iguape / Ilha Comprida",
      "Ilha Comprida",
      "Ilha Comprida / Pedrinhas",
      "Pariquera-Açu",
      "Itariri",
      "Juquiá",
      "Miracatu",
      "Pedro de Toledo",
      "Tapiraí",
      "Apiaí",
      "Barra do Chapéu",
      "Itaoca",
      "Itapirapuã Paulista",
      "Ribeira",
      "Ribeira / Itapirapuã Paulista",
      "Ribeira / Itaoca",
    ],
  ],
  ["Transporte", []],
  ["Controle De Perdas", []],
  [
    "Manutenção",
    ["Eletromecânica", "Automação", "Apiaí", "Juquitiba / São Lourenço", "Técnico", "Almoxarifado", "Cananéia", "Iguape", "Informatica"],
  ],
]);

export const localOptions = [
  { value: "Apiaí", label: "Apiaí" },
  { value: "Barra do Chapéu", label: "Barra do Chapéu" },
  { value: "São Lourenço", label: "São Lourenço" },
  { value: "Juquitiba", label: "Juquitiba" },
  { value: "Registro / Sete Barras", label: "Registro / Sete Barras" },
  { value: "Registro", label: "Registro" },
  { value: "Sete Barras", label: "Sete Barras" },
  { value: "Barra do Turvo", label: "Barra do Turvo" },
  { value: "Cajati", label: "Cajati" },
  { value: "Cajati / Jacupiranga", label: "Cajati / Jacupiranga" },
  { value: "Eldorado", label: "Eldorado" },
  { value: "Iporanga", label: "Iporanga" },
  { value: "Jacupiranga", label: "Jacupiranga" },
  { value: "Cananéia", label: "Cananéia" },
  { value: "Iguape", label: "Iguape" },
  { value: "Iguape / Ilha Comprida", label: "Iguape / Ilha Comprida" },
  { value: "Ilha Comprida", label: "Ilha Comprida" },
  { value: "Ilha Comprida / Pedrinhas", label: "Ilha Comprida / Pedrinhas" },
  { value: "Pariquera-Açu", label: "Pariquera-Açu" },
  { value: "Itariri", label: "Itariri" },
  { value: "Juquiá", label: "Juquiá" },
  { value: "Miracatu", label: "Miracatu" },
  { value: "Pedro de Toledo", label: "Pedro de Toledo" },
  { value: "Tapiraí", label: "Tapiraí" },
  { value: "Itaoca", label: "Itaoca" },
  { value: "Itapirapuã Paulista", label: "Itapirapuã Paulista" },
  { value: "Ribeira", label: "Ribeira" },
  { value: "Ribeira / Itapirapuã Paulista", label: "Ribeira / Itapirapuã Paulista" },
];
